# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b9d087a4132e040b3212e8b02dc296981a28ddaffd09463bf8732e8093c91395487c747433614ecb2969ce40c750561282d4572db0427d82c3356e1551c4d22

test:
  secret_key_base: 7137f13029d02824c45c2747493263efd3204e80f10a908d9376519e34d68daa12f7db98ecedd7475bb9487df3a5c943f17c7b6fd4ee6342c020a92c436275e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
